name: Deploy
run-name: Deploy by ${{ github.actor }}
on: 
    workflow_dispatch:
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev 
         
     
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1    

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: examples/EKSexamples
        run: terraform init

      - name: Terraform Plan
        working-directory: examples/EKSexamples
        run: |
            terraform plan -out=tfplan
            terraform show -no-color tfplan > plan.txt
            cat plan.txt